import Head from 'next/head'
import Image from 'next/image'
import requests from '../utils/requests'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'

export default function Home({res}) {
  
  return (
    <div >
      <Head>
        <title>hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={res.results}/>
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;

  const result = await fetch(`https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTrending.url
  }`
  ).then(res => res.json());
  return {
    props: {
        res: result
    }
  }
}